### ISSUE TITLE
CBCT source parameter

### ISSUE THREAD

**Issue by tsiewert** [medicalphysics/OpenXRayMC#4]
Hi,

I'm trying to use opendxmc for some CBCT dose simulations in a thesis and I have some questions regarding the parameter.
- Is the "Dose Area Product for beam" per exposure/frame or for the total CBCT span?
- Is it possible to reduce the Cone beam step angle below 0.5°? From the source.hpp it seems that the minStep ist 180°/360° -> 0.5°, changing this does not change the minimum in the gui.

Many thanks!

**Comment by medicalphysics** [comment]
Hi,

The DAP is for the total scan.  If you need better statistics you may also increase number of particles per exposure.

In the development version a bit has happened to the physics model and beam output to dose calibration. In addition the minimum CBCT step angle is 0.1 deg. I would recommend the development version since it's more tested. If you are unable to compile it (requires a custom build of VTK 9.3) I can provide windows binaries at the end of next week. 

Please note that the code is not validated and there are no guaranties for correctness ;)

**Comment by tsiewert** [comment]
Hi,

thank you very much for the reply.
The development version sounds great. Unfortunately I can't compile it on the machine at work. Would be great to get a precompiled version :)

I'm planning to compare and validate the simulations with measurements from an alderson phantom. If you want, I can share it with you once I got some results.

Cheers

**Comment by medicalphysics** [comment]
A new release is available now. I'm very interested in your results, are you doing film dosimetry for internal doses?

**Comment by tsiewert** [comment]
Thank you very much! I will it test as soon as I'm back from vacation. 
I planning to use TLD rods. Mostly in the head region for neuro-radiological exams.

**Comment by tsiewert** [comment]
Hi,
testing the new 1.2.1 version I found some differences to the old version for the CBCT:
- the half value layer in Al (mm) is different for the same tube voltage (i.e. 90 kV 1.0.2: 6,4 mm; 1.2.1: 4,7 mm)
- Collimation angles in the new version need to be half of the old version to get the same appearance in the image
- Convention on the Source angles (old: primary angle and new: start angle) seems to be different.
- Collimation angle and angle step are not correctly saved or loaded. 
- And the field size is missing
- The beam outlines are shown on every slice of the phantom if you scroll through it in z direction

For comparison I have attached an image side by side of the two versions.
![ComparisonOpenDXMC](https://github.com/user-attachments/assets/1f45facc-f2f4-422f-91ba-0120ee094f62)

**Comment by medicalphysics** [comment]
Thanks for the comparison, I've published a new release (1.2.3) with a bugfix for the HVL calculation. It's now more inline with results from the specpy application. I've also fixed the collimation angles so that they display full angles and not halves. The hdf5 saves should now include all CBCTbeam attributes. 

The beam outlines bug is still present due to the complete rewrite of the display code to support joint window leveling and navigation.
